name: Run Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
    
    - name: Run tests
      run: |
        cd app
        go test -v
      
    - name: Fail if tests fail
      if: failure()
      uses: actions/github-script@v6
      with:
        script: |
          core.setFailed('Tests failed')
